let playerMonsters = {
  default: {
    name: "Frontier Village",
    type: "fire",
    encounterEnergy: 0,
    encounterBlock: 0,
    startingEnergy: 0,
    opponentMoveIndex: false,
    cardPool: fireCardPool,
    maxHP: 45,
    currentHP: 45,
    strength: 0,
    dex: 0,
    tempStrength: 0,
    tempDex: 0,
    fightStrength: 0,
    fightDex: 0,
    turnEnergy: 3,
    turnCards: 6,
    avatar: "img/fireMonster.png",
    startingDeck: [
    //5 attack
    basicCardsNew.swordSlash,
    basicCardsNew.swordSlash,
    basicCardsNew.overheadSwing,
    basicCardsNew.bowShot,
    basicCardsNew.bowShot,
    //5 defense
    basicCardsNew.shieldBlock,
    basicCardsNew.shieldBlock,
    basicCardsNew.shieldBlock,
    basicCardsNew.shieldBlock,
    basicCardsNew.shieldBlock,
    ],
  },

  swirly: testPlayerMonster,

    charles: {
      name: "Mountain Stronghold",
      type: "fire",
      encounterEnergy: 0,
      startingEnergy: 0,
      encounterBlock: 0,
      opponentMoveIndex: false,
      cardPool: fireCardPool,
      maxHP: 50,
      currentHP: 50,
      strength: 0,
      dex: 0,
      tempStrength: 0,
      tempDex: 0,
      fightStrength: 0,
      fightDex: 0,
      turnEnergy: 3,
      turnCards: 6,
      avatar: "img/flamingbaby.png",
      startingDeck: [
        fireCardPool.fireenergy,
        fireCardPool.fireenergy,
        fireCardPool.fireenergy,
        fireCardPool.fireenergy,
        cards.tackle,
        cards.tackle,
        fireCardPool.gainstrength,
        cards.withdraw,
        cards.withdraw,
      ],
    },

    recall: {
      name: "River Kingdom",
      type: "water",
      encounterEnergy: 0,
      startingEnergy: 0,
      opponentMoveIndex: false,
      cardPool: waterCardPool,
      maxHP: 50,
      currentHP: 50,
      strength: 0,
      dex: 0,
      tempStrength: 0,
      tempDex: 0,
      fightStrength: 0,
      fightDex: 0,
      turnEnergy: 3,
      turnCards: 6,
      avatar: "img/easy/adorablefire.png",
      startingDeck: [
        waterCardPool.waterenergy,
        waterCardPool.waterenergy,
        waterCardPool.waterenergy,
        waterCardPool.waterenergy,
        waterCardPool.recall,
        waterCardPool.ascension,
        waterCardPool.meditate,
        cards.tackle,
        cards.withdraw,
        cards.withdraw,
        cards.withdraw,
      ],
    },

    devCheat: {
      name: "Testing Village",
      type: "air",
      encounterEnergy: 0,
      startingEnergy: 0,
      opponentMoveIndex: false,
      cardPool: simpleCardPool,
      maxHP: 50,
      currentHP: 50,
      strength: 0,
      dex: 0,
      tempStrength: 0,
      tempDex: 0,
      fightStrength: 0,
      fightDex: 0,
      turnEnergy: 3,
      turnCards: 6,
      avatar: "img/playerturtle.png",
      startingDeck: [
        cards.makeshiftforge,
        cards.rareFireEnergy,
        cards.reformingshield,
        specialCardPool.testkill,
        cards.buildwatchtower,
        cards.buildbarricade,
        cards.demolish,
      ],
    },
};

// Legacy opponent definitions (kept for reference)
let oldMonsters = {};
